// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactIntl from "react-intl";
import * as JsxRuntime from "react/jsx-runtime";

let FormattedMessage = {};

JsxRuntime.jsx((function (prim) {
  return ReactIntl.FormattedMessage(prim);
}), {
  id: "test",
  defaultMessage: "Test"
});

export {
  FormattedMessage,
}
/*  Not a pure module */
